-- PlotService: builds a per-player stadium plot at runtime.
-- Removes the need to hand-place and tag building models in Studio.
-- Each building model carries:
--   * a StringValue "BuildingId"  (matches BuildingConfig ids)
--   * an ObjectValue "Owner"      (the player who owns this plot)
--   * the CollectionService tag "StadiumBuilding"
--   * a BillboardGui "InfoBillboard" with NameLabel, LevelLabel, UpgradeButton
-- The client (StadiumController) wires the buttons/click detectors for the owner.

local Players           = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local CollectionService = game:GetService("CollectionService")
local Workspace         = game:GetService("Workspace")
local ServerScriptService = game:GetService("ServerScriptService")

local BuildingConfig = require(ReplicatedStorage.Config.BuildingConfig)
local DataService    = require(ServerScriptService.DataService)

local PlotService = {}

-- ─── Plot layout constants ───────────────────────────────────────────────────

local PLOT_SIZE = Vector3.new(180, 1, 180)

-- The city sits dead centre; claimable plots ring it in a 5x5 grid (centre cell =
-- the city) so the centre really is in the middle of all the plots. Sorted
-- closest-first so VIP players get the prime spots nearest the city and free
-- players the outer ones. SPACING/centre must match HubService's road grid.
local CITY_CENTER = Vector3.new(0, 0, -700)   -- must equal HubService HUB_ORIGIN
local PLOT_SPACING = 300
local PLOT_SLOTS = {}
do
	for i = -2, 2 do
		for j = -2, 2 do
			if not (i == 0 and j == 0) then   -- centre cell is the city itself
				table.insert(PLOT_SLOTS, CITY_CENTER + Vector3.new(i * PLOT_SPACING, 0, j * PLOT_SPACING))
			end
		end
	end
	table.sort(PLOT_SLOTS, function(a, b)
		return (a - CITY_CENTER).Magnitude < (b - CITY_CENTER).Magnitude
	end)
end

-- Hand-placed building spots (offset from plot origin, on the ground plane). The
-- central pitch occupies x[-40,40] z[-48,48]; buildings live in the margins around
-- it so nothing sits ON the field. Entrance/spawn is south (-Z); all face -Z.
local BUILDING_LAYOUT = {
	stands      = { x = -18, z =  70 },   -- north stand, set well back behind the goal
	bigscreen   = { x =  46, z =  70 },   -- north-east, beside the stand
	floodlights = { x = -72, z =  72 },   -- north-west corner tower
	concessions = { x = -70, z =  18 },   -- west concourse, faces the pitch (east)
	merch       = { x =  70, z =  18 },   -- east concourse, faces the pitch (west)
	parking     = { x =  64, z = -64 },   -- south-east corner, clear of the pitch
}

-- Parody team palette (NO real club/national colors).
local TEAM_GOLD  = Color3.fromRGB(245, 210,  60)
local CONCRETE   = Color3.fromRGB(120, 124, 134)
local METAL_DARK = Color3.fromRGB( 45,  48,  58)
local M = Enum.Material

-- Each building is composed of several anchored parts. Piece #1 is the
-- interactive base (carries the ClickDetector + info billboard + collision).
-- `offset` = part-center position relative to the building's ground point.
local BUILDING_PIECES = {
	-- Just a concrete foundation; the raked seating rows are generated by
	-- buildStandTiers() and GROW with the stands' upgrade level.
	stands = {
		{ size = Vector3.new(46, 3, 26), offset = Vector3.new(0, 1.5, 0), color = CONCRETE, material = M.Concrete },
	},
	-- A proper snack-bar storefront. Front faces -Z (rotated to face the pitch).
	concessions = {
		{ size = Vector3.new(15, 10, 12),    offset = Vector3.new(0,  5.0,  1.0),  color = Color3.fromRGB(243,232,205), material = M.SmoothPlastic, collide = true },  -- plaster body (base)
		{ size = Vector3.new(11, 4.6, 0.6),  offset = Vector3.new(0,  5.6, -5.0),  color = Color3.fromRGB(34,38,46),    material = M.SmoothPlastic, collide = true },  -- dark serving window
		{ size = Vector3.new(12.6, 1.3, 2.6),offset = Vector3.new(0,  3.0, -6.0),  color = Color3.fromRGB(150,110,70),  material = M.WoodPlanks,    collide = true },  -- counter shelf
		{ size = Vector3.new(15.6, 0.8, 4.6),offset = Vector3.new(0,  8.1, -6.2),  color = Color3.fromRGB(208,70,70),   material = M.SmoothPlastic, collide = false }, -- red awning
		{ size = Vector3.new(15.6, 0.85,1.5),offset = Vector3.new(0,  8.15,-7.7),  color = Color3.fromRGB(245,245,245), material = M.SmoothPlastic, collide = false }, -- white awning trim
		{ size = Vector3.new(16.5, 1.5, 13), offset = Vector3.new(0, 10.5,  1.0),  color = Color3.fromRGB(150,60,55),   material = M.SmoothPlastic, collide = true },  -- roof
	},
	-- A retail store with a glass storefront + display window.
	merch = {
		{ size = Vector3.new(15, 11, 12),    offset = Vector3.new(0,  5.5,  1.0),  color = Color3.fromRGB(54,92,168),   material = M.SmoothPlastic, collide = true },  -- store body (base)
		{ size = Vector3.new(12, 7.0, 0.5),  offset = Vector3.new(0,  5.0, -5.0),  color = Color3.fromRGB(182,216,245), material = M.Glass,         collide = true },  -- glass front
		{ size = Vector3.new(2.0, 7.0, 0.7), offset = Vector3.new(0,  5.0, -5.1),  color = Color3.fromRGB(235,238,248), material = M.SmoothPlastic, collide = false }, -- window mullion
		{ size = Vector3.new(15.6, 0.9, 4.2),offset = Vector3.new(0,  9.1, -6.0),  color = TEAM_GOLD,                   material = M.SmoothPlastic, collide = false }, -- gold awning
		{ size = Vector3.new(16.5, 1.5, 13), offset = Vector3.new(0, 11.5,  1.0),  color = Color3.fromRGB(38,64,130),   material = M.SmoothPlastic, collide = true },  -- roof
		{ size = Vector3.new(16.5, 1.8, 1.0),offset = Vector3.new(0, 12.6, -5.4),  color = TEAM_GOLD,                   material = M.SmoothPlastic, collide = false }, -- sign band
	},
	parking = {
		{ size = Vector3.new(26, 0.6, 20), offset = Vector3.new(0,  0.3, 0), color = Color3.fromRGB(60,62,68),    material = M.Concrete },
		{ size = Vector3.new(0.4, 0.66, 16),offset = Vector3.new(-6, 0.34,0),color = Color3.fromRGB(235,235,235), material = M.SmoothPlastic },
		{ size = Vector3.new(0.4, 0.66, 16),offset = Vector3.new(0,  0.34,0),color = Color3.fromRGB(235,235,235), material = M.SmoothPlastic },
		{ size = Vector3.new(0.4, 0.66, 16),offset = Vector3.new(6,  0.34,0),color = Color3.fromRGB(235,235,235), material = M.SmoothPlastic },
	},
	bigscreen = {
		{ size = Vector3.new(22, 16, 2),   offset = Vector3.new(0, 9, 0),     color = METAL_DARK,                  material = M.Metal },
		{ size = Vector3.new(19, 13, 0.6), offset = Vector3.new(0, 9, -1.05), color = Color3.fromRGB(120,210,255), material = M.Neon },
		{ size = Vector3.new(1.4, 9, 1.4), offset = Vector3.new(-8, 4.5, 0.7),color = METAL_DARK,                  material = M.Metal },
		{ size = Vector3.new(1.4, 9, 1.4), offset = Vector3.new(8,  4.5, 0.7),color = METAL_DARK,                  material = M.Metal },
	},
	floodlights = {
		{ size = Vector3.new(1.4, 22, 1.4),offset = Vector3.new(0, 11, 0),    color = Color3.fromRGB(90,95,105),   material = M.Metal },
		{ size = Vector3.new(6, 1.6, 3),   offset = Vector3.new(0, 21.6, 0),  color = METAL_DARK,                  material = M.Metal },
		{ size = Vector3.new(5, 1.2, 2.4), offset = Vector3.new(0, 22.4, 0.3),color = Color3.fromRGB(255,250,210), material = M.Neon },
	},
}

local DEFAULT_PIECES = {
	{ size = Vector3.new(10,10,10), offset = Vector3.new(0,5,0), color = Color3.fromRGB(150,150,150), material = M.SmoothPlastic },
}

-- Uploaded surface textures (decals on the AC6005 account, via Open Cloud).
local TEXTURES = {
	grass   = "rbxassetid://70872978008715",
	seats   = "rbxassetid://107539265030237",
	brick   = "rbxassetid://100402802088606",
	metal   = "rbxassetid://110788642331092",
	asphalt = "rbxassetid://129383393602486",
}

-- Tile a texture across the given faces of a part.
local function applyTexture(part, textureId, studs, faces)
	if not part or not textureId then return end
	for _, face in ipairs(faces) do
		local t = Instance.new("Texture")
		t.Texture      = textureId
		t.Face         = face
		t.StudsPerTileU = studs
		t.StudsPerTileV = studs
		t.Parent       = part
	end
end

local ALL_SIDES = {
	Enum.NormalId.Front, Enum.NormalId.Back, Enum.NormalId.Left, Enum.NormalId.Right,
}

-- Invented parody sponsors for the pitch-side advertising boards (no real brands).
local SPONSORS = {
	"BRAINROT ENERGY", "THE GOBLET", "NEON COLA", "MEME MOBILE",
	"SUS BANK", "GOBLINPAY", "RIZZ FUEL", "OHIO AIR",
}

-- Folder that holds all live plots
local plotsFolder = Workspace:FindFirstChild("Plots")
if not plotsFolder then
	plotsFolder = Instance.new("Folder")
	plotsFolder.Name = "Plots"
	plotsFolder.Parent = Workspace
end

-- Each base brings its own solid, collidable ground pad (built in buildPlot).
-- Pads are placed edge-to-edge in a row, so together they read as one connected
-- ground — but every base always has guaranteed solid footing under it.

-- ─── Plot index allocation ───────────────────────────────────────────────────

local usedSlots         = {}      -- slotIndex -> player.UserId
local playerPlotIndex   = {}      -- player.UserId -> slotIndex (into PLOT_SLOTS)
local playerPlotModel   = {}      -- player.UserId -> plot Model
local playerSpawnCFrame = {}      -- player.UserId -> CFrame to (re)spawn at
local playerConns       = {}      -- player.UserId -> CharacterAdded connection
local emptyPlots        = {}      -- slotIndex -> "OPEN PLOT" placeholder Model

-- Put the player on their plot's entrance, now and on every respawn.
local function teleportToPlot(player)
	local cf = playerSpawnCFrame[player.UserId]
	if not cf then return end
	local char = player.Character or player.CharacterAdded:Wait()
	local hrp  = char:WaitForChild("HumanoidRootPart", 10)
	if hrp then
		hrp.CFrame = cf
	end
end

-- A dim "OPEN PLOT" placeholder so the world looks populated and players can see
-- where the unclaimed plots are. Replaced by a real plot when someone claims it.
local function buildEmptyPlot(slot)
	if emptyPlots[slot] then return end
	local origin = PLOT_SLOTS[slot]
	if not origin then return end

	local m = Instance.new("Model")
	m.Name = "OpenPlot_" .. slot

	local pad = Instance.new("Part")
	pad.Name = "Ground"; pad.Anchored = true; pad.CanCollide = true
	pad.Size = Vector3.new(PLOT_SIZE.X, 1, PLOT_SIZE.Z)
	pad.Position = origin + Vector3.new(0, -0.5, 0)   -- top at y = 0
	pad.Color = Color3.fromRGB(58, 76, 60); pad.Material = Enum.Material.Grass
	pad.TopSurface = Enum.SurfaceType.Smooth; pad.BottomSurface = Enum.SurfaceType.Smooth
	pad.Parent = m
	applyTexture(pad, TEXTURES.grass, 24, { Enum.NormalId.Top })
	m.PrimaryPart = pad

	-- A flat painted border (NOT glowing neon posts — those lit up the whole skyline
	-- and were visual spam). Reads as a reserved, marked-out lot instead.
	local function border(sx, sz, ox, oz)
		local b = Instance.new("Part")
		b.Anchored = true; b.CanCollide = false
		b.Size = Vector3.new(sx, 0.4, sz)
		b.Position = origin + Vector3.new(ox, 0.2, oz)
		b.Color = Color3.fromRGB(220, 178, 55); b.Material = Enum.Material.SmoothPlastic
		b.Parent = m
	end
	local hw, hl = PLOT_SIZE.X/2 - 2, PLOT_SIZE.Z/2 - 2
	border(PLOT_SIZE.X - 4, 2.5, 0,  hl)   -- north edge
	border(PLOT_SIZE.X - 4, 2.5, 0, -hl)   -- south edge
	border(2.5, PLOT_SIZE.Z - 4,  hw, 0)   -- east edge
	border(2.5, PLOT_SIZE.Z - 4, -hw, 0)   -- west edge

	local sign = Instance.new("Part")
	sign.Name = "Sign"; sign.Anchored = true; sign.CanCollide = false
	sign.Transparency = 1; sign.Size = Vector3.new(2, 2, 2)
	sign.Position = origin + Vector3.new(0, 12, 0); sign.Parent = m
	local bb = Instance.new("BillboardGui")
	bb.Size = UDim2.new(0, 250, 0, 72); bb.AlwaysOnTop = true; bb.MaxDistance = 700
	bb.Adornee = sign; bb.Parent = sign
	local lbl = Instance.new("TextLabel")
	lbl.Size = UDim2.new(1, 0, 1, 0); lbl.BackgroundTransparency = 1
	lbl.Text = "🏗️ OPEN PLOT\nclaimed when a player joins"
	lbl.TextColor3 = Color3.fromRGB(255, 235, 150); lbl.TextScaled = true
	lbl.Font = Enum.Font.GothamBold; lbl.TextStrokeTransparency = 0.4; lbl.Parent = bb

	m.Parent = plotsFolder
	emptyPlots[slot] = m
end

local function removeEmptyPlot(slot)
	local m = emptyPlots[slot]
	if m then m:Destroy(); emptyPlots[slot] = nil end
end

-- Allocate the best available slot. VIP players take the CLOSEST free slot; free
-- players take the FARTHEST — so the prime, close-to-city spots are a VIP perk.
local function allocateSlot(player)
	local data  = DataService.getData(player)
	local isVip = data and data.passes and data.passes.vip
	local chosen
	if isVip then
		for i = 1, #PLOT_SLOTS do
			if not usedSlots[i] then chosen = i; break end
		end
	else
		for i = #PLOT_SLOTS, 1, -1 do
			if not usedSlots[i] then chosen = i; break end
		end
	end
	if not chosen then
		-- Grid full (more players than slots): overflow onto slot 1.
		for i = 1, #PLOT_SLOTS do
			if not usedSlots[i] then chosen = i; break end
		end
		chosen = chosen or 1
	end
	usedSlots[chosen] = player.UserId
	playerPlotIndex[player.UserId] = chosen
	removeEmptyPlot(chosen)
	return chosen
end

local function freeSlot(player)
	local i = playerPlotIndex[player.UserId]
	if i ~= nil then
		usedSlots[i] = nil
		playerPlotIndex[player.UserId] = nil
	end
	return i
end

-- ─── Building model builder ──────────────────────────────────────────────────

local function buildBillboard(buildingCfg)
	local billboard = Instance.new("BillboardGui")
	billboard.Name           = "InfoBillboard"
	billboard.Size           = UDim2.new(0, 180, 0, 90)
	billboard.StudsOffset    = Vector3.new(0, 4, 0)
	billboard.AlwaysOnTop    = true
	billboard.MaxDistance    = 80
	billboard.LightInfluence = 0

	local bg = Instance.new("Frame")
	bg.Name                 = "Frame"
	bg.Size                 = UDim2.new(1, 0, 1, 0)
	bg.BackgroundColor3     = Color3.fromRGB(15, 15, 22)
	bg.BackgroundTransparency = 0.25
	bg.BorderSizePixel      = 0
	bg.Parent               = billboard
	local c = Instance.new("UICorner") c.CornerRadius = UDim.new(0, 8) c.Parent = bg

	local nameLabel = Instance.new("TextLabel")
	nameLabel.Name             = "NameLabel"
	nameLabel.Size             = UDim2.new(1, -8, 0, 26)
	nameLabel.Position         = UDim2.new(0, 4, 0, 2)
	nameLabel.BackgroundTransparency = 1
	nameLabel.Text             = buildingCfg.name
	nameLabel.TextColor3       = Color3.fromRGB(255, 255, 255)
	nameLabel.TextScaled       = true
	nameLabel.Font             = Enum.Font.GothamBold
	nameLabel.Parent           = bg

	local levelLabel = Instance.new("TextLabel")
	levelLabel.Name             = "LevelLabel"
	levelLabel.Size             = UDim2.new(1, -8, 0, 22)
	levelLabel.Position         = UDim2.new(0, 4, 0, 28)
	levelLabel.BackgroundTransparency = 1
	levelLabel.Text             = "Locked"
	levelLabel.TextColor3       = Color3.fromRGB(180, 180, 200)
	levelLabel.TextScaled       = true
	levelLabel.Font             = Enum.Font.Gotham
	levelLabel.Parent           = bg

	local upgradeButton = Instance.new("TextButton")
	upgradeButton.Name             = "UpgradeButton"
	upgradeButton.Size             = UDim2.new(1, -16, 0, 30)
	upgradeButton.Position         = UDim2.new(0, 8, 1, -34)
	upgradeButton.BackgroundColor3 = Color3.fromRGB(50, 180, 80)
	upgradeButton.Text             = "Upgrade"
	upgradeButton.TextColor3       = Color3.fromRGB(255, 255, 255)
	upgradeButton.TextScaled       = true
	upgradeButton.Font             = Enum.Font.GothamBold
	upgradeButton.Parent           = bg
	local bc = Instance.new("UICorner") bc.CornerRadius = UDim.new(0, 6) bc.Parent = upgradeButton

	return billboard
end

-- ─── Signage ─────────────────────────────────────────────────────────────────

-- A lit storefront banner on a part's front (-Z) face.
local function addBoothSign(part, text, color)
	local sg = Instance.new("SurfaceGui")
	sg.Name          = "Sign"
	sg.Face          = Enum.NormalId.Front     -- -Z, toward the concourse
	sg.SizingMode    = Enum.SurfaceGuiSizingMode.PixelsPerStud
	sg.PixelsPerStud = 50
	sg.LightInfluence = 0                       -- full-bright so it "lights up"
	sg.Parent        = part

	-- Near the very top of the storefront face, so the awning can't cover it.
	local board = Instance.new("Frame")
	board.Size = UDim2.new(1, 0, 0.2, 0)
	board.Position = UDim2.new(0, 0, 0.02, 0)
	board.BackgroundColor3 = Color3.fromRGB(15, 15, 22)
	board.BackgroundTransparency = 0.12
	board.BorderSizePixel = 0
	board.Parent = sg
	local stroke = Instance.new("UIStroke")
	stroke.Color = color
	stroke.Thickness = 3
	stroke.Parent = board

	local label = Instance.new("TextLabel")
	label.Size = UDim2.new(1, -8, 1, -6)
	label.Position = UDim2.new(0, 4, 0, 3)
	label.BackgroundTransparency = 1
	label.Text = text
	label.TextColor3 = color
	label.TextScaled = true
	label.Font = Enum.Font.GothamBlack
	label.Parent = board
end

-- A glowing live scoreboard on the big-screen's Neon face (parody teams only).
local function addScoreboard(part)
	local sg = Instance.new("SurfaceGui")
	sg.Name          = "Scoreboard"
	sg.Face          = Enum.NormalId.Front
	sg.SizingMode    = Enum.SurfaceGuiSizingMode.PixelsPerStud
	sg.PixelsPerStud = 40
	sg.LightInfluence = 0
	sg.Parent        = part

	local bg = Instance.new("Frame")
	bg.Size = UDim2.new(1, 0, 1, 0)
	bg.BackgroundColor3 = Color3.fromRGB(6, 10, 18)
	bg.BorderSizePixel = 0
	bg.Parent = sg

	local title = Instance.new("TextLabel")
	title.Size = UDim2.new(1, 0, 0.24, 0)
	title.BackgroundTransparency = 1
	title.Text = "⚽ THE BRAINROT CUP"
	title.TextColor3 = Color3.fromRGB(255, 210, 70)
	title.TextScaled = true
	title.Font = Enum.Font.GothamBlack
	title.Parent = bg

	local row = Instance.new("Frame")
	row.Size = UDim2.new(1, 0, 0.5, 0)
	row.Position = UDim2.new(0, 0, 0.26, 0)
	row.BackgroundTransparency = 1
	row.Parent = bg

	local function teamChip(xScale, code, col)
		local chip = Instance.new("TextLabel")
		chip.Size = UDim2.new(0.3, 0, 0.7, 0)
		chip.Position = UDim2.new(xScale, 0, 0.15, 0)
		chip.BackgroundColor3 = col
		chip.Text = code
		chip.TextColor3 = Color3.new(1, 1, 1)
		chip.TextScaled = true
		chip.Font = Enum.Font.GothamBlack
		chip.Parent = row
		local c = Instance.new("UICorner") c.CornerRadius = UDim.new(0, 8) c.Parent = chip
		local s = Instance.new("UIStroke") s.Color = Color3.new(0, 0, 0) s.Thickness = 2 s.Parent = chip
	end
	teamChip(0.04, "GRN", Color3.fromRGB(45, 165, 85))
	teamChip(0.66, "AZL", Color3.fromRGB(60, 120, 220))

	local score = Instance.new("TextLabel")
	score.Size = UDim2.new(0.32, 0, 1, 0)
	score.Position = UDim2.new(0.34, 0, 0, 0)
	score.BackgroundTransparency = 1
	score.Text = "2 - 1"
	score.TextColor3 = Color3.new(1, 1, 1)
	score.TextScaled = true
	score.Font = Enum.Font.GothamBlack
	score.Parent = row

	local live = Instance.new("TextLabel")
	live.Size = UDim2.new(1, 0, 0.2, 0)
	live.Position = UDim2.new(0, 0, 0.78, 0)
	live.BackgroundTransparency = 1
	live.Text = "🔴 LIVE"
	live.TextColor3 = Color3.fromRGB(255, 80, 80)
	live.TextScaled = true
	live.Font = Enum.Font.GothamBold
	live.Parent = bg
end

-- A gentle ambient sparkle on Neon surfaces (best-effort built-in texture).
local function addGlow(part, color)
	local att = Instance.new("Attachment")
	att.Parent = part
	local pe = Instance.new("ParticleEmitter")
	pe.Texture      = "rbxasset://textures/particles/sparkles_main.dds"
	pe.Color        = ColorSequence.new(color)
	pe.Lifetime     = NumberRange.new(0.8, 1.5)
	pe.Rate         = 5
	pe.Speed        = NumberRange.new(1, 2)
	pe.SpreadAngle  = Vector2.new(45, 45)
	pe.Size         = NumberSequence.new(0.7)
	pe.Transparency = NumberSequence.new(0.35)
	pe.Parent       = att
end

-- Raked seating rows for the stands that GROW with the upgrade level. Each row
-- steps up and back; more rows = a taller, fuller grandstand. Re-runnable: it
-- clears its old rows first, so it doubles as the "regrow on upgrade" path.
-- (baseX, baseZ) is the stands' world position; rows sit on its y=3 foundation.
local SPECTATOR_SHIRTS = {
	Color3.fromRGB(222, 72, 72),  Color3.fromRGB(70, 120, 222), Color3.fromRGB(245, 205, 55),
	Color3.fromRGB(60, 182, 104), Color3.fromRGB(232, 232, 238), Color3.fromRGB(160, 92, 210),
	Color3.fromRGB(250, 140, 40),
}

local function buildStandTiers(model, baseX, baseZ, level)
	-- Clear previously-built dynamic stand parts (re-runnable for live regrow).
	for _, c in ipairs(model:GetChildren()) do
		if c.Name == "StandPart" then c:Destroy() end
	end

	local rows     = math.clamp(level, 1, 8)   -- seating rows grow with level
	local stepUp   = 2.2
	local stepBack = 2.6
	local W        = 40                          -- stand width
	local frontZ   = baseZ - 6                   -- front row (nearest the pitch)
	local backZ    = frontZ + (rows - 1) * stepBack
	local midZ     = (frontZ + backZ) / 2
	local depth    = (backZ - frontZ) + 8
	local seatTopY = 3 + rows * stepUp           -- y at the top of the seating bank
	local roofY    = seatTopY + 8                -- canopy floats high overhead (real clearance)

	local STEP_C = Color3.fromRGB(74, 78, 92)
	local WALL_C = Color3.fromRGB(88, 92, 106)
	local ROOF_C = Color3.fromRGB(38, 42, 52)
	local GOLD   = Color3.fromRGB(245, 205, 55)
	local GREEN  = Color3.fromRGB(48, 170, 90)
	local SKIN   = Color3.fromRGB(236, 200, 168)

	local function part(sx, sy, sz, x, y, z, color, mat, collide, shape)
		local p = Instance.new("Part")
		p.Name          = "StandPart"
		p.Anchored      = true
		p.CanCollide    = collide ~= false
		p.Size          = Vector3.new(sx, sy, sz)
		p.Position      = Vector3.new(x, y, z)
		p.Color         = color
		p.Material      = mat or Enum.Material.SmoothPlastic
		p.TopSurface    = Enum.SurfaceType.Smooth
		p.BottomSurface = Enum.SurfaceType.Smooth
		if shape then p.Shape = shape end
		p.Parent        = model
		return p
	end

	-- A simple seated spectator (torso + ball head), purely decorative crowd.
	local function spectator(x, yTop, z)
		local shirt = SPECTATOR_SHIRTS[math.random(1, #SPECTATOR_SHIRTS)]
		part(0.95, 1.25, 0.75, x, yTop + 0.75, z, shirt, Enum.Material.SmoothPlastic, false)
		part(0.72, 0.72, 0.72, x, yTop + 1.7, z, SKIN, Enum.Material.SmoothPlastic, false, Enum.PartType.Ball)
	end

	-- Raked rows: a solid concrete step + a colored (textured) seat bench on each,
	-- with a crowd that fills in as the stand grows taller.
	for i = 1, rows do
		local z = frontZ + (i - 1) * stepBack
		local y = 3 + (i - 1) * stepUp
		part(W, stepUp, stepBack + 0.3, baseX, y + stepUp / 2, z, STEP_C, Enum.Material.Concrete, true)
		local bench = part(W - 2, 1.0, 1.5, baseX, y + stepUp + 0.5, z + 0.55,
			(i % 2 == 0) and GOLD or GREEN, Enum.Material.SmoothPlastic, true)
		applyTexture(bench, TEXTURES.seats, 4, { Enum.NormalId.Top, Enum.NormalId.Front })

		-- Crowd on this row (skip the front-row centre — reserved for player seats).
		local benchY = y + stepUp + 1.0
		local cols   = 7
		local spanX  = W - 8
		for k = 0, cols - 1 do
			local x = baseX - spanX / 2 + (spanX / (cols - 1)) * k
			local frontCentre = (i == 1 and math.abs(x - baseX) < 6)
			if not frontCentre and math.random() < 0.82 then
				spectator(x, benchY, z + 0.35)
			end
		end
	end

	-- Player-sittable seats on the front-row centre (sit & watch the match).
	local seatY = 3 + stepUp + 0.55
	for s = -2, 2 do
		local seat = Instance.new("Seat")
		seat.Name        = "StandPart"
		seat.Anchored    = true
		seat.Size        = Vector3.new(2, 0.5, 2)
		seat.Position    = Vector3.new(baseX + s * 2.3, seatY, frontZ + 0.4)
		seat.Color       = Color3.fromRGB(250, 215, 70)
		seat.Material    = Enum.Material.SmoothPlastic
		seat.TopSurface  = Enum.SurfaceType.Smooth
		seat.Parent      = model
	end

	-- Back wall (brick) behind the top row.
	local back = part(W, roofY, 2, baseX, roofY / 2, backZ + 2, WALL_C, Enum.Material.Concrete, true)
	applyTexture(back, TEXTURES.brick, 10, ALL_SIDES)

	-- Two side walls enclosing the bank.
	part(2, roofY, depth, baseX - W / 2, roofY / 2, midZ, WALL_C, Enum.Material.Concrete, true)
	part(2, roofY, depth, baseX + W / 2, roofY / 2, midZ, WALL_C, Enum.Material.Concrete, true)

	-- Cantilevered roof canopy covering the WHOLE bank front-to-back. Because roofY
	-- and depth both scale with the row count, the canopy always shades every row
	-- (fixes the "cover too short as the stand grows" problem).
	part(W + 3, 1, depth + 6, baseX, roofY, midZ - 1, ROOF_C, Enum.Material.Metal, false)
	-- Front roof-support pillars rising from the apron to the canopy.
	part(1.6, roofY, 1.6, baseX - W / 2 + 2, roofY / 2, frontZ - 2, WALL_C, Enum.Material.Metal, true)
	part(1.6, roofY, 1.6, baseX + W / 2 - 2, roofY / 2, frontZ - 2, WALL_C, Enum.Material.Metal, true)

	-- A lit sponsor fascia under the roof's front edge (classic stadium detail).
	local fascia = part(W + 3, 2.2, 0.6, baseX, roofY - 1.6, frontZ - 4.7,
		Color3.fromRGB(18, 20, 28), Enum.Material.SmoothPlastic, false)
	local sg = Instance.new("SurfaceGui")
	sg.Name = "Sign"; sg.Face = Enum.NormalId.Front
	sg.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud; sg.PixelsPerStud = 40; sg.LightInfluence = 0
	sg.Parent = fascia
	local lbl = Instance.new("TextLabel")
	lbl.Size = UDim2.new(1, 0, 1, 0); lbl.BackgroundTransparency = 1
	lbl.Text = "🏟  " .. SPONSORS[1] .. " STAND"
	lbl.TextColor3 = Color3.fromRGB(255, 210, 70); lbl.TextScaled = true; lbl.Font = Enum.Font.GothamBlack
	lbl.Parent = sg
end

local function buildBuildingModel(buildingCfg, position, player, level)
	local pieces = BUILDING_PIECES[buildingCfg.id] or DEFAULT_PIECES

	local model = Instance.new("Model")
	model.Name = buildingCfg.id

	local primary
	local partsByIndex = {}
	for i, p in ipairs(pieces) do
		local part = Instance.new("Part")
		part.Name          = (i == 1) and "Base" or ("Piece" .. i)
		part.Size          = p.size
		part.Position      = position + p.offset
		part.Anchored      = true
		local collide = p.collide
		if collide == nil then collide = (i == 1) end  -- default: only the base blocks
		part.CanCollide    = collide
		part.Color         = p.color
		part.Material       = p.material or Enum.Material.SmoothPlastic
		part.TopSurface    = Enum.SurfaceType.Smooth
		part.BottomSurface = Enum.SurfaceType.Smooth
		part.Parent        = model
		partsByIndex[i] = part
		if p.material == Enum.Material.Neon then
			addGlow(part, p.color)
		end
		if i == 1 then primary = part end
	end
	model.PrimaryPart = primary

	-- Surface textures per building
	local id = buildingCfg.id
	if id == "stands" then
		-- Generate the raked seating rows for the current level (grows on upgrade).
		buildStandTiers(model, position.X, position.Z, level or 1)
	elseif id == "parking" then
		applyTexture(partsByIndex[1], TEXTURES.asphalt, 12, { Enum.NormalId.Top })
	elseif id == "bigscreen" then
		applyTexture(partsByIndex[1], TEXTURES.metal, 8, ALL_SIDES)
	elseif id == "floodlights" then
		applyTexture(partsByIndex[1], TEXTURES.metal, 5, ALL_SIDES)
	end

	local idValue = Instance.new("StringValue")
	idValue.Name   = "BuildingId"
	idValue.Value  = buildingCfg.id
	idValue.Parent = model

	local ownerValue = Instance.new("ObjectValue")
	ownerValue.Name   = "Owner"
	ownerValue.Value  = player
	ownerValue.Parent = model

	-- ClickDetector for active-collect buildings (client decides whether to use it)
	local detector = Instance.new("ClickDetector")
	detector.MaxActivationDistance = 32
	detector.Parent = primary

	buildBillboard(buildingCfg).Parent = primary

	-- Flavor signage
	if buildingCfg.id == "concessions" then
		addBoothSign(primary, "🍔 SNACKS", Color3.fromRGB(255, 175, 60))
	elseif buildingCfg.id == "merch" then
		addBoothSign(primary, "👕 MERCH", Color3.fromRGB(95, 160, 255))
	elseif buildingCfg.id == "bigscreen" then
		addScoreboard(partsByIndex[2] or primary)   -- the Neon screen face
	end

	CollectionService:AddTag(model, "StadiumBuilding")

	return model
end

-- Perimeter wall (with a south entrance gap) + two goal frames, for "place" feel.
local function buildSurrounds(plot, origin)
	local half = PLOT_SIZE.X / 2
	local wallH, wallT = 10, 2          -- tall enough that you can't jump over it
	local wallColor = Color3.fromRGB(70, 74, 86)

	local function wall(cx, cz, sx, sz)
		local p = Instance.new("Part")
		p.Anchored = true
		p.Size = Vector3.new(sx, wallH, sz)
		p.Position = origin + Vector3.new(cx, wallH / 2, cz)
		p.Color = wallColor
		p.Material = Enum.Material.Concrete
		p.TopSurface = Enum.SurfaceType.Smooth
		p.BottomSurface = Enum.SurfaceType.Smooth
		p.Parent = plot
		applyTexture(p, TEXTURES.brick, 12, ALL_SIDES)

		local horizontal = sx > sz
		local sgnZ = (cz > 0) and 1 or ((cz < 0) and -1 or 0)
		local sgnX = (cx > 0) and 1 or ((cx < 0) and -1 or 0)

		-- Roof canopy: a slab on top that cantilevers inward over the stands.
		local canopy = Instance.new("Part")
		canopy.Anchored   = true
		canopy.CanCollide = true
		canopy.Color      = Color3.fromRGB(48, 52, 62)
		canopy.Material   = Enum.Material.Metal
		if horizontal then
			canopy.Size     = Vector3.new(sx + 4, 2.5, 16)
			canopy.Position = origin + Vector3.new(cx, wallH + 1.25, cz - sgnZ * 7)
		else
			canopy.Size     = Vector3.new(16, 2.5, sz + 4)
			canopy.Position = origin + Vector3.new(cx - sgnX * 7, wallH + 1.25, cz)
		end
		canopy.Parent = plot

		-- Buttress pillars spaced along the wall (rise just above it).
		local span  = horizontal and sx or sz
		local count = math.max(2, math.floor(span / 26))
		for k = 0, count do
			local t = -span / 2 + (span / count) * k
			local pil = Instance.new("Part")
			pil.Anchored = true
			pil.Material  = Enum.Material.Concrete
			pil.Color     = Color3.fromRGB(88, 92, 106)
			pil.Size      = Vector3.new(horizontal and 5 or 3, wallH + 2.5, horizontal and 3 or 5)
			if horizontal then
				pil.Position = origin + Vector3.new(cx + t, (wallH + 2.5) / 2, cz + sgnZ * 1.4)
			else
				pil.Position = origin + Vector3.new(cx + sgnX * 1.4, (wallH + 2.5) / 2, cz + t)
			end
			pil.Parent = plot
		end
	end

	wall(0,  half, PLOT_SIZE.X, wallT)   -- north
	wall( half, 0, wallT, PLOT_SIZE.Z)   -- east
	wall(-half, 0, wallT, PLOT_SIZE.Z)   -- west
	local sideW = (PLOT_SIZE.X - 24) / 2 -- south wall split for a centre entrance
	wall(-(12 + sideW / 2), -half, sideW, wallT)
	wall( (12 + sideW / 2), -half, sideW, wallT)

	-- Two simple white goal frames framing the central lane.
	local function goal(cz)
		local function bar(dx, dy, sx, sy, sz)
			local p = Instance.new("Part")
			p.Anchored = true
			p.CanCollide = true
			p.Size = Vector3.new(sx, sy, sz)
			p.Position = origin + Vector3.new(dx, dy, cz)
			p.Color = Color3.fromRGB(240, 240, 245)
			p.Material = Enum.Material.SmoothPlastic
			p.Parent = plot
		end
		bar(-7, 4, 1, 8, 1)    -- left post
		bar( 7, 4, 1, 8, 1)    -- right post
		bar( 0, 8, 15, 1, 1)   -- crossbar
	end
	goal(44)
	goal(-44)
end

-- A striped grass pitch with white markings in the centre, so the grounds read
-- as an actual stadium instead of an empty floor. Buildings frame it.
local function buildPitch(plot, origin)
	local PX, PZ = 80, 96

	local function flat(cx, cz, sx, sz, color, yy, material)
		local p = Instance.new("Part")
		p.Anchored = true
		p.CanCollide = false
		p.Size = Vector3.new(sx, 0.2, sz)
		p.Position = origin + Vector3.new(cx, yy, cz)
		p.Color = color
		p.Material = material or Enum.Material.Grass
		p.TopSurface = Enum.SurfaceType.Smooth
		p.BottomSurface = Enum.SurfaceType.Smooth
		p.Parent = plot
	end

	-- Mowed stripes — PROCEDURAL, so the pitch always reads as a pitch even if the
	-- grass texture is still moderating or unavailable. When the texture does load
	-- it sits underneath these on the field and shows on the surrounding ground.
	local stripes = 8
	local sw = PX / stripes
	for i = 0, stripes - 1 do
		-- High-contrast alternating bands so the "mowed pitch" reads clearly on top
		-- of the (uniform) grass texture below. Lifted to y=0.3 to avoid z-fighting.
		local shade = (i % 2 == 0) and Color3.fromRGB(72, 168, 90) or Color3.fromRGB(32, 98, 50)
		flat(-PX / 2 + sw / 2 + i * sw, 0, sw, PZ, shade, 0.30)
	end

	-- White field markings (sit just above the stripes)
	local white = Color3.fromRGB(238, 240, 244)
	local function line(cx, cz, sx, sz)
		flat(cx, cz, sx, sz, white, 0.42, Enum.Material.SmoothPlastic)
	end
	line(0,  PZ / 2, PX, 1)   -- north line
	line(0, -PZ / 2, PX, 1)   -- south line
	line( PX / 2, 0, 1, PZ)   -- east line
	line(-PX / 2, 0, 1, PZ)   -- west line
	line(0, 0, PX, 1)         -- halfway line
	line(0, 0, 4, 4)          -- centre spot
end

-- LED advertising hoardings ringing the pitch (parody sponsors) — a classic
-- stadium detail. Low boards just outside the touchlines, facing the field.
local function buildHoardings(plot, origin)
	local PX, PZ = 80, 96
	local seg = 18
	local idx = 0
	local cols = {
		Color3.fromRGB(255, 80, 80), Color3.fromRGB(80, 200, 255),
		Color3.fromRGB(120, 230, 140), Color3.fromRGB(255, 200, 60),
	}

	local function board(cx, cz, sx, sz, face)
		local p = Instance.new("Part")
		p.Anchored   = true
		p.CanCollide = true
		p.Size       = Vector3.new(sx, 2.4, sz)
		p.Position   = origin + Vector3.new(cx, 1.3, cz)
		p.Color      = Color3.fromRGB(18, 20, 28)
		p.Material   = Enum.Material.SmoothPlastic
		p.Parent     = plot

		local sg = Instance.new("SurfaceGui")
		sg.Face          = face
		sg.SizingMode    = Enum.SurfaceGuiSizingMode.PixelsPerStud
		sg.PixelsPerStud = 40
		sg.LightInfluence = 0
		sg.Parent        = p
		local lbl = Instance.new("TextLabel")
		lbl.Size = UDim2.new(1, 0, 1, 0)
		lbl.BackgroundTransparency = 1
		lbl.Text = SPONSORS[(idx % #SPONSORS) + 1]
		lbl.TextColor3 = cols[(idx % #cols) + 1]
		lbl.TextScaled = true
		lbl.Font = Enum.Font.GothamBlack
		lbl.Parent = sg
		idx = idx + 1
	end

	for x = -PX / 2 + seg / 2, PX / 2 - seg / 2, seg do
		board(x,  PZ / 2 + 1, seg - 2, 0.6, Enum.NormalId.Front)   -- north touchline
		board(x, -PZ / 2 - 1, seg - 2, 0.6, Enum.NormalId.Back)    -- south touchline
	end
	for z = -PZ / 2 + seg / 2, PZ / 2 - seg / 2, seg do
		board( PX / 2 + 1, z, 0.6, seg - 2, Enum.NormalId.Left)    -- east
		board(-PX / 2 - 1, z, 0.6, seg - 2, Enum.NormalId.Right)   -- west
	end
end

-- A force-field gate across the entrance + an owner-only toggle button.
-- Closed: touching it insta-kills NON-owners (the owner passes freely).
-- Open:   anyone may walk in. Owner clicks the button to open/close.
local function buildDoor(plot, origin, player)
	local entranceCF = origin + Vector3.new(0, 4, -PLOT_SIZE.Z / 2)

	local door = Instance.new("Part")
	door.Name       = "BaseDoor"
	door.Anchored   = true
	door.CanCollide  = false               -- kill-curtain, not a physical block
	door.Size       = Vector3.new(24, 8, 1)  -- full wall height so it can't be jumped
	door.Position   = entranceCF
	door.Material   = Enum.Material.ForceField
	door.Parent     = plot
	door:SetAttribute("Closed", true)

	local function paintDoor()
		local closed = door:GetAttribute("Closed")
		door.Color        = closed and Color3.fromRGB(220, 60, 60) or Color3.fromRGB(70, 210, 110)
		door.Transparency = closed and 0.25 or 0.7
	end
	paintDoor()

	-- Insta-kill intruders crossing a closed door.
	door.Touched:Connect(function(hit)
		if not door:GetAttribute("Closed") then return end
		local character = hit and hit.Parent
		local hum = character and character:FindFirstChildOfClass("Humanoid")
		if not hum or hum.Health <= 0 then return end
		local toucher = Players:GetPlayerFromCharacter(character)
		if not toucher or toucher == player then return end   -- owner is immune
		hum.Health = 0
	end)

	-- Owner-only toggle button just inside the entrance.
	local button = Instance.new("Part")
	button.Name      = "DoorButton"
	button.Anchored  = true
	button.Size      = Vector3.new(4, 2, 4)
	button.Position  = origin + Vector3.new(11, 1, -PLOT_SIZE.Z / 2 + 9)
	button.Material  = Enum.Material.Neon
	button.Parent    = plot

	local cd = Instance.new("ClickDetector")
	cd.MaxActivationDistance = 20
	cd.Parent = button

	local bb = Instance.new("BillboardGui")
	bb.Size = UDim2.new(0, 150, 0, 32)
	bb.StudsOffset = Vector3.new(0, 2.2, 0)
	bb.AlwaysOnTop = true
	bb.MaxDistance = 60
	bb.Adornee = button
	bb.Parent = button
	local lbl = Instance.new("TextLabel")
	lbl.Size = UDim2.new(1, 0, 1, 0)
	lbl.BackgroundTransparency = 1
	lbl.TextScaled = true
	lbl.Font = Enum.Font.GothamBold
	lbl.TextColor3 = Color3.new(1, 1, 1)
	lbl.Parent = bb

	local function paintButton()
		local closed = door:GetAttribute("Closed")
		button.Color = closed and Color3.fromRGB(220, 60, 60) or Color3.fromRGB(70, 210, 110)
		lbl.Text     = closed and "🚪 Door: CLOSED" or "🚪 Door: OPEN"
	end
	paintButton()

	cd.MouseClick:Connect(function(clicker)
		if clicker ~= player then return end   -- only the base owner controls the gate
		door:SetAttribute("Closed", not door:GetAttribute("Closed"))
		paintDoor()
		paintButton()
	end)
end

-- A neon "Ride Kart" station near the parking lot. Tagged "KartSpawner" so
-- KartService can wire its click → spawn the owner's kart right here.
local function buildKartStation(plot, origin, player)
	local pos = origin + Vector3.new(64, 0.6, -40)

	local pad = Instance.new("Part")
	pad.Name        = "KartStation"
	pad.Anchored    = true
	pad.Size        = Vector3.new(9, 1.2, 9)
	pad.Position    = pos
	pad.Material    = Enum.Material.Neon
	pad.Color       = Color3.fromRGB(90, 200, 255)
	pad.TopSurface  = Enum.SurfaceType.Smooth
	pad.Parent      = plot
	applyTexture(pad, TEXTURES.asphalt, 6, { Enum.NormalId.Top })

	local owner = Instance.new("ObjectValue")
	owner.Name  = "Owner"
	owner.Value = player
	owner.Parent = pad

	local cd = Instance.new("ClickDetector")
	cd.Name = "KartClick"
	cd.MaxActivationDistance = 28
	cd.Parent = pad

	local bb = Instance.new("BillboardGui")
	bb.Size        = UDim2.new(0, 180, 0, 58)
	bb.StudsOffset = Vector3.new(0, 3.4, 0)
	bb.AlwaysOnTop = true
	bb.MaxDistance = 75
	bb.Adornee     = pad
	bb.Parent      = pad
	local frame = Instance.new("Frame")
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundColor3 = Color3.fromRGB(15, 15, 22)
	frame.BackgroundTransparency = 0.25
	frame.BorderSizePixel = 0
	frame.Parent = bb
	local fc = Instance.new("UICorner") fc.CornerRadius = UDim.new(0, 8) fc.Parent = frame
	local t = Instance.new("TextLabel")
	t.Size = UDim2.new(1, -8, 0.56, 0)
	t.Position = UDim2.new(0, 4, 0, 2)
	t.BackgroundTransparency = 1
	t.Text = "🏎 RIDE KART"
	t.TextColor3 = Color3.fromRGB(150, 235, 255)
	t.TextScaled = true
	t.Font = Enum.Font.GothamBlack
	t.Parent = frame
	local s = Instance.new("TextLabel")
	s.Size = UDim2.new(1, -8, 0.4, 0)
	s.Position = UDim2.new(0, 4, 0.57, 0)
	s.BackgroundTransparency = 1
	s.Text = "Click to spawn"
	s.TextColor3 = Color3.fromRGB(200, 200, 220)
	s.TextScaled = true
	s.Font = Enum.Font.Gotham
	s.Parent = frame

	CollectionService:AddTag(pad, "KartSpawner")
end

-- A pad that teleports the player to the shared Brainrot City hub (HubService
-- wires the actual teleport via the "ToCityPad" tag).
local function buildCityPad(plot, origin, player)
	local pos = origin + Vector3.new(24, 0.6, -PLOT_SIZE.Z / 2 + 12)

	local pad = Instance.new("Part")
	pad.Name        = "ToCityPad"
	pad.Anchored    = true
	pad.Size        = Vector3.new(10, 1.2, 10)
	pad.Position    = pos
	pad.Material    = Enum.Material.Neon
	pad.Color       = Color3.fromRGB(255, 170, 55)
	pad.TopSurface  = Enum.SurfaceType.Smooth
	pad.Parent      = plot

	local owner = Instance.new("ObjectValue")
	owner.Name  = "Owner"
	owner.Value = player
	owner.Parent = pad

	-- Click (not touch) so you don't get yanked away while walking your plot.
	local cd = Instance.new("ClickDetector")
	cd.Name = "CityClick"
	cd.MaxActivationDistance = 26
	cd.Parent = pad

	local bb = Instance.new("BillboardGui")
	bb.Size        = UDim2.new(0, 200, 0, 56)
	bb.StudsOffset = Vector3.new(0, 3.4, 0)
	bb.AlwaysOnTop = true
	bb.MaxDistance = 80
	bb.Adornee     = pad
	bb.Parent      = pad
	local frame = Instance.new("Frame")
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundColor3 = Color3.fromRGB(15, 15, 22)
	frame.BackgroundTransparency = 0.25
	frame.BorderSizePixel = 0
	frame.Parent = bb
	local fcc = Instance.new("UICorner") fcc.CornerRadius = UDim.new(0, 8) fcc.Parent = frame
	local t = Instance.new("TextLabel")
	t.Size = UDim2.new(1, -8, 0.56, 0)
	t.Position = UDim2.new(0, 4, 0, 2)
	t.BackgroundTransparency = 1
	t.Text = "🏙 BRAINROT CITY"
	t.TextColor3 = Color3.fromRGB(255, 195, 90)
	t.TextScaled = true
	t.Font = Enum.Font.GothamBlack
	t.Parent = frame
	local s = Instance.new("TextLabel")
	s.Size = UDim2.new(1, -8, 0.4, 0)
	s.Position = UDim2.new(0, 4, 0.57, 0)
	s.BackgroundTransparency = 1
	s.Text = "⭐ VIP: click to teleport"
	s.TextColor3 = Color3.fromRGB(255, 215, 120)
	s.TextScaled = true
	s.Font = Enum.Font.Gotham
	s.Parent = frame

	CollectionService:AddTag(pad, "ToCityPad")
end

-- A second level you climb to: stairs → viewing deck → Trophy Room + VIP Lounge.
-- Built once per plot in a clear east-side spot.
local function buildUpperTier(plot, origin, player)
	local bx, bz = 70, 22       -- deck centre (plot-local)
	local deckY  = 18
	local function up(sx, sy, sz, x, y, z, color, mat, collide)
		local p = Instance.new("Part")
		p.Name = "UpperTier"
		p.Anchored = true
		p.CanCollide = collide ~= false
		p.Size = Vector3.new(sx, sy, sz)
		p.Position = origin + Vector3.new(x, y, z)
		p.Color = color
		p.Material = mat or Enum.Material.SmoothPlastic
		p.TopSurface = Enum.SurfaceType.Smooth
		p.BottomSurface = Enum.SurfaceType.Smooth
		p.Parent = plot
		return p
	end
	local CONCRETE = Color3.fromRGB(86, 90, 104)
	local GOLD     = Color3.fromRGB(245, 205, 70)

	-- Support cores at the BACK corners only — never in the staircase path.
	up(6, deckY, 6, bx - 17, deckY / 2, bz + 16, CONCRETE, Enum.Material.Concrete)
	up(6, deckY, 6, bx + 17, deckY / 2, bz + 16, CONCRETE, Enum.Material.Concrete)

	-- Wide staircase up the SOUTH face, landing flush on the deck (auto-climbable).
	local steps = 13
	for i = 1, steps do
		local y = i * (deckY / steps)
		local z = bz - 36 + (i - 1) * (18 / (steps - 1))
		up(16, 0.9, 2.4, bx, y, z, CONCRETE, Enum.Material.Concrete)
	end

	-- Viewing deck
	local deck = up(40, 1.5, 36, bx, deckY, bz, CONCRETE, Enum.Material.Concrete)
	applyTexture(deck, TEXTURES.brick, 8, { Enum.NormalId.Top })
	-- Railings — SOLID walls so you can't fall off the deck (south is OPEN for stairs)
	up(1, 4, 36, bx + 20, deckY + 2, bz, GOLD, Enum.Material.Metal, true)
	up(1, 4, 36, bx - 20, deckY + 2, bz, GOLD, Enum.Material.Metal, true)
	up(40, 4, 1, bx, deckY + 2, bz + 18, GOLD, Enum.Material.Metal, true)

	-- ── Trophy Room (west half; open to the deck, with a LIVE display board) ──
	local trX = bx - 11
	up(0.6, 9, 20, trX - 9, deckY + 5, bz, Color3.fromRGB(40,44,58), Enum.Material.Concrete)  -- west wall
	up(20, 9, 0.6, trX, deckY + 5, bz + 9.5, Color3.fromRGB(40,44,58), Enum.Material.Concrete) -- back wall
	up(20, 1, 20, trX, deckY + 9.5, bz, Color3.fromRGB(34,38,50), Enum.Material.Metal)         -- roof
	for i = -1, 1 do
		up(3, 2, 3, trX + i * 5.5, deckY + 1.5, bz + 5, Color3.fromRGB(60,64,78), Enum.Material.Concrete)
		up(1.6, 2.4, 1.6, trX + i * 5.5, deckY + 3.7, bz + 5, GOLD, Enum.Material.Neon)
	end
	local trBoard = up(18, 6.5, 0.4, trX, deckY + 5.5, bz - 9, Color3.fromRGB(12,14,22), Enum.Material.SmoothPlastic)
	trBoard.Name = "TrophyDisplay"
	local trOwner = Instance.new("ObjectValue") trOwner.Name = "Owner" trOwner.Value = player trOwner.Parent = trBoard
	local trSg = Instance.new("SurfaceGui")
	trSg.Name = "Info"; trSg.Face = Enum.NormalId.Back; trSg.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	trSg.PixelsPerStud = 22; trSg.LightInfluence = 0; trSg.Parent = trBoard
	local trTitle = Instance.new("TextLabel")
	trTitle.Size = UDim2.new(1,0,0.26,0); trTitle.BackgroundTransparency = 1; trTitle.Text = "🏆 TROPHY ROOM"
	trTitle.TextColor3 = GOLD; trTitle.TextScaled = true; trTitle.Font = Enum.Font.GothamBlack; trTitle.Parent = trSg
	local trInfo = Instance.new("TextLabel")
	trInfo.Name = "Lines"; trInfo.Size = UDim2.new(1,-8,0.72,0); trInfo.Position = UDim2.new(0,4,0.27,0)
	trInfo.BackgroundTransparency = 1; trInfo.Text = "Win cup matches to fill your case!"
	trInfo.TextColor3 = Color3.fromRGB(225,225,240); trInfo.TextScaled = true; trInfo.Font = Enum.Font.Gotham
	trInfo.TextWrapped = true; trInfo.Parent = trSg
	CollectionService:AddTag(trBoard, "TrophyDisplay")

	-- ── VIP Lounge (east half; OPEN, advertises perks to everyone) ──
	local vlX = bx + 11
	up(16, 0.4, 18, vlX, deckY + 1, bz, Color3.fromRGB(70, 40, 90), Enum.Material.Neon, false)  -- plush floor
	local vlBoard = up(16, 7, 0.4, vlX, deckY + 5.5, bz + 8.8, Color3.fromRGB(20,16,28), Enum.Material.SmoothPlastic)
	local vlSg = Instance.new("SurfaceGui")
	vlSg.Face = Enum.NormalId.Front; vlSg.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	vlSg.PixelsPerStud = 20; vlSg.LightInfluence = 0; vlSg.Parent = vlBoard
	local vlTitle = Instance.new("TextLabel")
	vlTitle.Size = UDim2.new(1,0,0.2,0); vlTitle.BackgroundTransparency = 1; vlTitle.Text = "⭐ VIP PERKS"
	vlTitle.TextColor3 = Color3.fromRGB(255,215,120); vlTitle.TextScaled = true; vlTitle.Font = Enum.Font.GothamBlack; vlTitle.Parent = vlSg
	local vlList = Instance.new("TextLabel")
	vlList.Size = UDim2.new(1,-10,0.62,0); vlList.Position = UDim2.new(0,5,0.22,0); vlList.BackgroundTransparency = 1
	vlList.Text = "• Instant City teleport\n• VIP Turbo Kart (way faster)\n• Daily free gems\n• This exclusive lounge"
	vlList.TextColor3 = Color3.new(1,1,1); vlList.TextScaled = true; vlList.Font = Enum.Font.Gotham
	vlList.TextXAlignment = Enum.TextXAlignment.Left; vlList.Parent = vlSg
	local vlCta = Instance.new("TextLabel")
	vlCta.Size = UDim2.new(1,0,0.16,0); vlCta.Position = UDim2.new(0,0,0.84,0); vlCta.BackgroundTransparency = 1
	vlCta.Text = "Get VIP in the 🛍 Shop!"; vlCta.TextColor3 = Color3.fromRGB(120,255,160); vlCta.TextScaled = true; vlCta.Font = Enum.Font.GothamBold; vlCta.Parent = vlSg
	up(5, 1.4, 2, vlX - 4, deckY + 1.7, bz - 5, Color3.fromRGB(120,60,150), Enum.Material.SmoothPlastic)
	up(5, 1.4, 2, vlX + 4, deckY + 1.7, bz - 5, Color3.fromRGB(120,60,150), Enum.Material.SmoothPlastic)
end

-- A rebirth/prestige pad (RebirthService wires the click via the "RebirthPad" tag).
local function buildRebirthPad(plot, origin, player)
	local pos = origin + Vector3.new(-24, 0.6, -PLOT_SIZE.Z / 2 + 12)

	local pad = Instance.new("Part")
	pad.Name        = "RebirthPad"
	pad.Anchored    = true
	pad.Size        = Vector3.new(10, 1.2, 10)
	pad.Position    = pos
	pad.Material    = Enum.Material.Neon
	pad.Color       = Color3.fromRGB(180, 90, 255)
	pad.TopSurface  = Enum.SurfaceType.Smooth
	pad.Parent      = plot

	local owner = Instance.new("ObjectValue")
	owner.Name = "Owner"; owner.Value = player; owner.Parent = pad

	local cd = Instance.new("ClickDetector")
	cd.Name = "RebirthClick"
	cd.MaxActivationDistance = 26
	cd.Parent = pad

	local bb = Instance.new("BillboardGui")
	bb.Size = UDim2.new(0, 200, 0, 56)
	bb.StudsOffset = Vector3.new(0, 3.4, 0)
	bb.AlwaysOnTop = true
	bb.MaxDistance = 80
	bb.Adornee = pad
	bb.Parent = pad
	local frame = Instance.new("Frame")
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundColor3 = Color3.fromRGB(15, 15, 22)
	frame.BackgroundTransparency = 0.25
	frame.BorderSizePixel = 0
	frame.Parent = bb
	local fcc = Instance.new("UICorner") fcc.CornerRadius = UDim.new(0, 8) fcc.Parent = frame
	local t = Instance.new("TextLabel")
	t.Size = UDim2.new(1, -8, 0.56, 0); t.Position = UDim2.new(0, 4, 0, 2)
	t.BackgroundTransparency = 1; t.Text = "🔁 REBIRTH"
	t.TextColor3 = Color3.fromRGB(210, 150, 255); t.TextScaled = true; t.Font = Enum.Font.GothamBlack
	t.Parent = frame
	local s = Instance.new("TextLabel")
	s.Size = UDim2.new(1, -8, 0.4, 0); s.Position = UDim2.new(0, 4, 0.57, 0)
	s.BackgroundTransparency = 1; s.Text = "Reset for +50% income"
	s.TextColor3 = Color3.fromRGB(200, 200, 220); s.TextScaled = true; s.Font = Enum.Font.Gotham
	s.Parent = frame

	CollectionService:AddTag(pad, "RebirthPad")
end

-- Non-stands buildings visibly GROW with their upgrade level so progression is
-- felt. Scales around the centre, then re-seats the base on the ground (y=0).
local function scaleBuildingToLevel(model, level)
	local base = model.PrimaryPart
	if not base then return end
	local targetScale = 1 + math.clamp(level, 0, 24) * 0.03   -- up to ~1.7x at high levels
	model:ScaleTo(targetScale)
	local baseBottom = base.Position.Y - base.Size.Y / 2
	if math.abs(baseBottom) > 0.001 then
		model:TranslateBy(Vector3.new(0, -baseBottom, 0))
	end
end

-- ─── Plot builder ────────────────────────────────────────────────────────────

function PlotService.buildPlot(player)
	-- Avoid duplicate plots if called twice
	if playerPlotModel[player.UserId] then
		return playerPlotModel[player.UserId]
	end

	local slot   = allocateSlot(player)
	local origin = PLOT_SLOTS[slot]

	local plot = Instance.new("Model")
	plot.Name = "Plot_" .. player.UserId

	-- Solid, collidable ground pad — the single guaranteed walking surface for the
	-- whole base. Top sits exactly at y = 0; everything else is placed on top of it.
	local pad = Instance.new("Part")
	pad.Name         = "Ground"
	pad.Anchored     = true
	pad.CanCollide   = true
	pad.Size         = Vector3.new(PLOT_SIZE.X, 4, PLOT_SIZE.Z)
	pad.Position     = origin + Vector3.new(0, -2, 0)   -- top at y = 0
	pad.Color        = Color3.fromRGB(70, 112, 72)
	pad.Material     = Enum.Material.Grass
	pad.TopSurface   = Enum.SurfaceType.Smooth
	pad.BottomSurface = Enum.SurfaceType.Smooth
	pad.Parent       = plot
	plot.PrimaryPart = pad
	applyTexture(pad, TEXTURES.grass, 24, { Enum.NormalId.Top })   -- mowed-grass surface

	-- Owner reference + spawn point
	local ownerValue = Instance.new("ObjectValue")
	ownerValue.Name   = "Owner"
	ownerValue.Value  = player
	ownerValue.Parent = plot

	-- Entrance plaza spawn at the south edge, facing north into the grounds.
	local spawnPos = origin + Vector3.new(0, 1, -PLOT_SIZE.Z / 2 + 11)
	local spawnPad = Instance.new("Part")
	spawnPad.Name        = "PlotSpawn"
	spawnPad.Size        = Vector3.new(14, 1, 14)
	spawnPad.Position    = spawnPos
	spawnPad.Anchored    = true
	spawnPad.Color       = Color3.fromRGB(60, 64, 76)
	spawnPad.Material    = Enum.Material.Concrete
	spawnPad.TopSurface  = Enum.SurfaceType.Smooth
	spawnPad.Parent      = plot

	-- Floating base-name sign (visible over the walls, identifies whose base it is).
	local nameSign = Instance.new("BillboardGui")
	nameSign.Name        = "BaseName"
	nameSign.Size        = UDim2.new(0, 280, 0, 54)
	nameSign.StudsOffset = Vector3.new(0, 26, 0)
	nameSign.AlwaysOnTop = true
	nameSign.MaxDistance = 400
	nameSign.Adornee     = spawnPad
	nameSign.Parent      = spawnPad
	local nameLbl = Instance.new("TextLabel")
	nameLbl.Size = UDim2.new(1, 0, 1, 0)
	nameLbl.BackgroundTransparency = 1
	nameLbl.Text = player.DisplayName .. "'s Stadium"
	nameLbl.TextColor3 = Color3.fromRGB(255, 235, 150)
	nameLbl.TextScaled = true
	nameLbl.Font = Enum.Font.GothamBlack
	nameLbl.TextStrokeTransparency = 0.4
	nameLbl.Parent = nameSign

	-- Stored facing +Z so the player looks into their stadium on (re)spawn.
	playerSpawnCFrame[player.UserId] =
		CFrame.lookAt(spawnPos + Vector3.new(0, 3, 0), spawnPos + Vector3.new(0, 3, 10))

	-- Pitch in the centre, advertising hoardings, perimeter wall + goals, gate
	buildPitch(plot, origin)
	buildHoardings(plot, origin)
	buildSurrounds(plot, origin)
	buildDoor(plot, origin, player)
	buildKartStation(plot, origin, player)
	buildCityPad(plot, origin, player)
	buildRebirthPad(plot, origin, player)
	buildUpperTier(plot, origin, player)

	-- Place each building at its hand-picked spot (spacious, framing the plaza),
	-- built to its current upgrade level (stands grow their seating with level).
	local data = DataService.getData(player)
	for _, buildingCfg in ipairs(BuildingConfig.Buildings) do
		local spot = BUILDING_LAYOUT[buildingCfg.id] or { x = 0, z = 0 }
		local pos = Vector3.new(
			origin.X + spot.x,
			origin.Y,                 -- ground pad top is y = 0
			origin.Z + spot.z
		)
		local level = (data and data.stadium and data.stadium[buildingCfg.id]) or 0
		local m = buildBuildingModel(buildingCfg, pos, player, level)
		m.Parent = plot
		-- Turn the concourse shops so their storefronts face the pitch.
		if buildingCfg.id == "concessions" or buildingCfg.id == "merch" then
			local target = Vector3.new(origin.X, m:GetPivot().Position.Y, origin.Z + 6)
			m:PivotTo(CFrame.lookAt(m:GetPivot().Position, target))
		end
		if buildingCfg.id ~= "stands" and level > 0 then
			scaleBuildingToLevel(m, level)
		end
	end

	plot.Parent = plotsFolder
	playerPlotModel[player.UserId] = plot

	-- Teleport onto the plot now AND on every respawn (fixes spawning at world origin).
	playerConns[player.UserId] = player.CharacterAdded:Connect(function()
		teleportToPlot(player)
	end)
	task.spawn(teleportToPlot, player)

	return plot
end

-- Called after a successful upgrade so the stadium visibly builds up in real time.
function PlotService.onBuildingUpgraded(player, buildingId, level)
	local plot  = playerPlotModel[player.UserId]
	local index = playerPlotIndex[player.UserId]
	if not plot or not index then return end
	local model = plot:FindFirstChild(buildingId)
	if not model then return end

	if buildingId == "stands" then
		-- The grandstand rebuilds its seating/crowd/roof to the new level.
		local origin = PLOT_SLOTS[index]
		local spot   = BUILDING_LAYOUT.stands
		buildStandTiers(model, origin.X + spot.x, origin.Z + spot.z, level)
	else
		-- Everything else grows in scale.
		scaleBuildingToLevel(model, level)
	end
end

-- Where the player (re)spawns on their plot — used by HubService to send them home.
function PlotService.getSpawnCFrame(player)
	return playerSpawnCFrame[player.UserId]
end

function PlotService.removePlot(player)
	local conn = playerConns[player.UserId]
	if conn then
		conn:Disconnect()
		playerConns[player.UserId] = nil
	end
	playerSpawnCFrame[player.UserId] = nil

	local plot = playerPlotModel[player.UserId]
	if plot then
		plot:Destroy()
		playerPlotModel[player.UserId] = nil
	end
	-- Free the slot and put the "OPEN PLOT" placeholder back so the spot is reusable.
	local slot = freeSlot(player)
	if slot then buildEmptyPlot(slot) end
end

-- Build "OPEN PLOT" placeholders on every slot not currently claimed. Called once
-- at server start (after the city exists) so the world looks populated from join 1.
function PlotService.initWorld()
	for i = 1, #PLOT_SLOTS do
		if not usedSlots[i] then
			buildEmptyPlot(i)
		end
	end
end

return PlotService
