-- StadiumController: handles the 3D stadium plot interaction for the local player.
-- Buildings are runtime-generated by the server (PlotService), tagged "StadiumBuilding",
-- and carry a "BuildingId" StringValue + "Owner" ObjectValue + an "InfoBillboard".
--
-- For the OWNER's buildings this script:
--   * wires the billboard UpgradeButton  -> UpgradeBuilding remote
--   * wires the ClickDetector (active-collect buildings only) -> CollectBuilding remote
--   * keeps level / cost labels in sync on every ProfileUpdated

local Players           = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local CollectionService = game:GetService("CollectionService")
local TweenService      = game:GetService("TweenService")
local Debris            = game:GetService("Debris")

-- WaitForChild (not a direct index) so a slow-replicating Config on the client
-- can't throw at require time and take down the whole client boot.
local BuildingConfig = require(ReplicatedStorage:WaitForChild("Config"):WaitForChild("BuildingConfig"))

local StadiumController = {}

local LocalPlayer = Players.LocalPlayer
local Remotes

-- Track wired buildings so we can refresh their labels on profile updates.
-- Map: buildingId -> { model, part, levelLabel, upgradeButton, cfg, lastLevel }
local ownedBuildings = {}
local wiredModels    = setmetatable({}, { __mode = "k" })  -- model -> true (prevents double-wire)
local lastData = nil   -- most recent profile, to sync buildings wired after it arrives

-- ─── Helpers ─────────────────────────────────────────────────────────────────

local function abbreviate(n)
	if n >= 1e9 then return string.format("%.1fB", n / 1e9) end
	if n >= 1e6 then return string.format("%.1fM", n / 1e6) end
	if n >= 1e3 then return string.format("%.1fK", n / 1e3) end
	return tostring(n)
end

-- ─── Procedural feedback (no assets) ─────────────────────────────────────────

-- A floating label that rises off a part and fades out.
local function floatText(part, text, color)
	if not part then return end
	local bb = Instance.new("BillboardGui")
	bb.Size        = UDim2.new(0, 170, 0, 42)
	bb.StudsOffset = Vector3.new(0, part.Size.Y / 2 + 3, 0)
	bb.AlwaysOnTop = true
	bb.MaxDistance = 90
	bb.Adornee     = part
	bb.Parent      = part

	local lbl = Instance.new("TextLabel")
	lbl.Size = UDim2.new(1, 0, 1, 0)
	lbl.BackgroundTransparency = 1
	lbl.Text = text
	lbl.TextColor3 = color or Color3.fromRGB(255, 220, 60)
	lbl.TextScaled = true
	lbl.Font = Enum.Font.GothamBlack
	lbl.TextStrokeTransparency = 0.3
	lbl.Parent = bb

	local ti = TweenInfo.new(1.0, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)
	TweenService:Create(bb, ti, { StudsOffset = bb.StudsOffset + Vector3.new(0, 4, 0) }):Play()
	TweenService:Create(lbl, ti, { TextTransparency = 1, TextStrokeTransparency = 1 }):Play()
	Debris:AddItem(bb, 1.15)
end

-- A one-shot sparkle burst (best-effort: built-in particle texture).
local function burstSparkle(part, color)
	if not part then return end
	local att = Instance.new("Attachment")
	att.Parent = part
	local pe = Instance.new("ParticleEmitter")
	pe.Texture       = "rbxasset://textures/particles/sparkles_main.dds"
	pe.Color         = ColorSequence.new(color or Color3.fromRGB(255, 220, 60))
	pe.Lifetime      = NumberRange.new(0.4, 0.7)
	pe.Speed         = NumberRange.new(6, 11)
	pe.SpreadAngle   = Vector2.new(180, 180)
	pe.Rotation      = NumberRange.new(0, 360)
	pe.Size          = NumberSequence.new(1.1)
	pe.Rate          = 0
	pe.Parent        = att
	pe:Emit(16)
	Debris:AddItem(att, 1.0)
end

-- Apply a profile's state to one wired building (labels, cost, dimming, level-up fx).
local function applyToBuilding(buildingId, entry, data)
	local level = (data.stadium and data.stadium[buildingId]) or 0
	local cfg   = entry.cfg

	if entry.levelLabel then
		entry.levelLabel.Text = level > 0 and ("Level " .. level) or "Locked"
	end

	if entry.upgradeButton then
		local atMax = cfg.maxLevel > 0 and level >= cfg.maxLevel
		if atMax then
			entry.upgradeButton.Text = "MAX"
			entry.upgradeButton.BackgroundColor3 = Color3.fromRGB(90, 90, 110)
		else
			local cost = BuildingConfig.upgradeCost(buildingId, level)
			local verb = level <= 0 and "Build" or "Upgrade"
			entry.upgradeButton.Text = verb .. "  💰" .. abbreviate(cost)
			local affordable = (data.coins or 0) >= cost
			entry.upgradeButton.BackgroundColor3 = affordable
				and Color3.fromRGB(50, 180, 80)
				or  Color3.fromRGB(150, 70, 70)
		end
	end

	-- Dim the whole building while it's unbuilt (level 0)
	local t = level <= 0 and 0.6 or 0
	for _, d in ipairs(entry.model:GetDescendants()) do
		if d:IsA("BasePart") then
			d.Transparency = t
		end
	end

	-- Celebrate a level-up (skip the first sync, which just establishes state)
	if entry.lastLevel ~= nil and level > entry.lastLevel then
		floatText(entry.part, "⬆ Level " .. level, Color3.fromRGB(120, 230, 140))
		burstSparkle(entry.part, Color3.fromRGB(120, 230, 140))
	end
	entry.lastLevel = level
end

-- ─── Wiring a single building ────────────────────────────────────────────────

local function wireBuilding(model)
	-- Guard on the model instance (no yields before this) so a model can never be
	-- wired twice — a double-wire would double-fire the upgrade remote per click.
	if wiredModels[model] then return end
	wiredModels[model] = true

	-- The "StadiumBuilding" tag can replicate a beat BEFORE the model's value
	-- objects and the (deeply-nested) billboard arrive on the client. The old code
	-- used FindFirstChild and bailed on a miss with no retry, which left buildings
	-- permanently unwired → "can't upgrade anything". Wait for each piece instead.
	local idValue = model:FindFirstChild("BuildingId") or model:WaitForChild("BuildingId", 20)
	local buildingId = idValue and idValue.Value
	if not buildingId then return end

	local ownerValue = model:FindFirstChild("Owner") or model:WaitForChild("Owner", 20)
	if not ownerValue or ownerValue.Value ~= LocalPlayer then return end  -- not ours
	if ownedBuildings[buildingId] then return end                          -- already have ours

	local cfg  = BuildingConfig.ById[buildingId]
	if not cfg then return end
	local part = model.PrimaryPart
		or model:FindFirstChild("Base")
		or model:WaitForChild("Base", 20)
		or model:FindFirstChildWhichIsA("BasePart")
	if not part then return end

	local billboard     = part:WaitForChild("InfoBillboard", 20)
	local frame         = billboard and billboard:WaitForChild("Frame", 10)
	local levelLabel    = frame and frame:WaitForChild("LevelLabel", 10)
	local upgradeButton = frame and frame:WaitForChild("UpgradeButton", 10)

	ownedBuildings[buildingId] = {
		model         = model,
		part          = part,
		levelLabel    = levelLabel,
		upgradeButton = upgradeButton,
		cfg           = cfg,
		lastLevel     = nil,
	}

	-- Upgrade button → server
	if upgradeButton then
		upgradeButton.Activated:Connect(function()
			local remote = Remotes and Remotes:FindFirstChild("UpgradeBuilding")
			if remote then remote:FireServer(buildingId) end
		end)
	end

	-- Active-collect buildings: clicking the model collects coins
	if cfg.activeOnly then
		local detector = part:FindFirstChildOfClass("ClickDetector")
		if detector then
			detector.MouseClick:Connect(function(clickingPlayer)
				if clickingPlayer ~= LocalPlayer then return end
				local remote = Remotes and Remotes:FindFirstChild("CollectBuilding")
				if remote then remote:FireServer(buildingId) end
				-- Optimistic juice (the exact amount comes via the toast).
				floatText(part, "+ 💰", Color3.fromRGB(255, 220, 60))
				burstSparkle(part, Color3.fromRGB(255, 220, 60))
			end)
		end
	end

	-- If profile data already arrived, sync this building immediately so it
	-- doesn't sit on the default "Locked" until the next periodic update.
	if lastData then
		applyToBuilding(buildingId, ownedBuildings[buildingId], lastData)
	end
end

local function wireAll()
	for _, model in ipairs(CollectionService:GetTagged("StadiumBuilding")) do
		task.spawn(wireBuilding, model)
	end
	CollectionService:GetInstanceAddedSignal("StadiumBuilding"):Connect(function(model)
		task.spawn(wireBuilding, model)
	end)
end

-- ─── Profile-driven label refresh ───────────────────────────────────────────

function StadiumController.onProfileUpdated(data)
	if not data or not data.stadium then return end
	lastData = data
	for buildingId, entry in pairs(ownedBuildings) do
		applyToBuilding(buildingId, entry, data)
	end
end

function StadiumController.init(clientState)
	Remotes = clientState.remotes
	wireAll()
end

return StadiumController
