-- StadiumController: handles the 3D stadium plot interaction for the local player.
-- Buildings are runtime-generated by the server (PlotService), tagged "StadiumBuilding",
-- and carry a "BuildingId" StringValue + "Owner" ObjectValue + an "InfoBillboard".
--
-- For the OWNER's buildings this script:
--   * wires the billboard UpgradeButton  -> UpgradeBuilding remote
--   * wires the ClickDetector (active-collect buildings only) -> CollectBuilding remote
--   * keeps level / cost labels in sync on every ProfileUpdated

local Players           = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local CollectionService = game:GetService("CollectionService")

local BuildingConfig = require(ReplicatedStorage.Config.BuildingConfig)

local StadiumController = {}

local LocalPlayer = Players.LocalPlayer
local Remotes

-- Track wired buildings so we can refresh their labels on profile updates.
-- Map: buildingId -> { model, levelLabel, upgradeButton }
local ownedBuildings = {}

-- ─── Helpers ─────────────────────────────────────────────────────────────────

local function getBuildingId(model)
	local v = model:FindFirstChild("BuildingId")
	return v and v.Value or nil
end

local function isOwnedByLocal(model)
	local owner = model:FindFirstChild("Owner")
	return owner and owner.Value == LocalPlayer
end

local function abbreviate(n)
	if n >= 1e9 then return string.format("%.1fB", n / 1e9) end
	if n >= 1e6 then return string.format("%.1fM", n / 1e6) end
	if n >= 1e3 then return string.format("%.1fK", n / 1e3) end
	return tostring(n)
end

-- ─── Wiring a single building ────────────────────────────────────────────────

local function wireBuilding(model)
	if not isOwnedByLocal(model) then return end

	local buildingId = getBuildingId(model)
	if not buildingId then return end
	if ownedBuildings[buildingId] then return end  -- already wired

	local cfg  = BuildingConfig.ById[buildingId]
	local part = model.PrimaryPart or model:FindFirstChildWhichIsA("BasePart")
	if not cfg or not part then return end

	local billboard     = part:FindFirstChild("InfoBillboard")
	local frame         = billboard and billboard:FindFirstChildWhichIsA("Frame")
	local levelLabel    = frame and frame:FindFirstChild("LevelLabel")
	local upgradeButton = frame and frame:FindFirstChild("UpgradeButton")

	-- Upgrade button → server
	if upgradeButton then
		upgradeButton.Activated:Connect(function()
			Remotes:FindFirstChild("UpgradeBuilding"):FireServer(buildingId)
		end)
	end

	-- Active-collect buildings: clicking the model collects coins
	if cfg.activeOnly then
		local detector = part:FindFirstChildOfClass("ClickDetector")
		if detector then
			detector.MouseClick:Connect(function(clickingPlayer)
				if clickingPlayer ~= LocalPlayer then return end
				Remotes:FindFirstChild("CollectBuilding"):FireServer(buildingId)
			end)
		end
	end

	ownedBuildings[buildingId] = {
		model         = model,
		levelLabel    = levelLabel,
		upgradeButton = upgradeButton,
		cfg           = cfg,
	}
end

local function wireAll()
	for _, model in ipairs(CollectionService:GetTagged("StadiumBuilding")) do
		task.spawn(wireBuilding, model)
	end
	CollectionService:GetInstanceAddedSignal("StadiumBuilding"):Connect(function(model)
		task.spawn(wireBuilding, model)
	end)
end

-- ─── Profile-driven label refresh ───────────────────────────────────────────

function StadiumController.onProfileUpdated(data)
	local stadium = data and data.stadium
	if not stadium then return end

	for buildingId, entry in pairs(ownedBuildings) do
		local level = stadium[buildingId] or 0
		local cfg   = entry.cfg

		if entry.levelLabel then
			entry.levelLabel.Text = level > 0 and ("Level " .. level) or "Locked"
		end

		if entry.upgradeButton then
			local atMax = cfg.maxLevel > 0 and level >= cfg.maxLevel
			if atMax then
				entry.upgradeButton.Text = "MAX"
				entry.upgradeButton.BackgroundColor3 = Color3.fromRGB(90, 90, 110)
			else
				local cost = BuildingConfig.upgradeCost(buildingId, level)
				local verb = level <= 0 and "Build" or "Upgrade"
				entry.upgradeButton.Text = verb .. "  🪙" .. abbreviate(cost)
				-- Affordability tint
				local affordable = (data.coins or 0) >= cost
				entry.upgradeButton.BackgroundColor3 = affordable
					and Color3.fromRGB(50, 180, 80)
					or  Color3.fromRGB(150, 70, 70)
			end
		end

		-- Dim un-built buildings
		local primaryPart = entry.model.PrimaryPart or entry.model:FindFirstChildWhichIsA("BasePart")
		if primaryPart then
			primaryPart.Transparency = level <= 0 and 0.5 or 0
		end
	end
end

function StadiumController.init(clientState)
	Remotes = clientState.remotes
	wireAll()
end

return StadiumController
